### ISSUE TITLE
mcumgr-core could not be found

### ISSUE THREAD

**Issue by bfrog** [runtimeco/mcumgr-android#36]
Following the instructions, using implementation 'io.runtime.mcumgr:mcumgr-ble:0.7-alpha2' in my gradle file gets me an error saying mcumgr-core could not be resolved

changing alpha2 to alpha1 works but I'm assuming there's issues with the older library

**Comment by bgiori** [comment]
Hi Tom,

Sorry for the delay. Thanks for pointing this out. I will be sure to be more careful about making sure my uploaded archives are complete before releasing from now on 👍 

Please use:
```
implementation 'io.runtime.mcumgr:mcumgr-ble:0.7-alpha3'
```

**Comment by bgiori** [comment]
Closing this issue, please let me know if you have issues with alpha3.
